// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvhbsunovyhyngtiweye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aGJzdW5vdnloeW5ndGl3ZXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDkzMzEsImV4cCI6MjA3NDI4NTMzMX0.QhwiKKdMASyDpYgHUfHc9tjGkWhjBXL0wasgmZqavsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});